# AUTO GENERATED FILE - DO NOT EDIT

dashDataTable <- function(id=NULL, containerClassName=NULL, containerStyle=NULL, currentPage=NULL, currentRowsPerPage=NULL, currentClickedRow=NULL, currentDoubleClickedRow=NULL, currentSelectedRows=NULL, currentSorting=NULL, title=NULL, columns=NULL, data=NULL, keyField=NULL, striped=NULL, highlightOnHover=NULL, pointerOnHover=NULL, className=NULL, style=NULL, responsive=NULL, disabled=NULL, overflowY=NULL, overflowYOffset=NULL, dense=NULL, noTableHead=NULL, persistTableHead=NULL, direction=NULL, selectableRows=NULL, selectableRowsVisibleOnly=NULL, selectableRowsHighlight=NULL, selectableRowsNoSelectAll=NULL, sortServer=NULL, expandableRows=NULL, expandOnRowClicked=NULL, expandOnRowDoubleClicked=NULL, expandableRowsHideExpander=NULL, defaultSortField=NULL, defaultSortAsc=NULL, pagination=NULL, paginationServer=NULL, paginationDefaultPage=NULL, paginationPerPage=NULL, paginationRowsPerPageOptions=NULL, paginationTotalRows=NULL, noHeader=NULL, fixedHeader=NULL, fixedHeaderScrollHeight=NULL) {
    
    props <- list(id=id, containerClassName=containerClassName, containerStyle=containerStyle, currentPage=currentPage, currentRowsPerPage=currentRowsPerPage, currentClickedRow=currentClickedRow, currentDoubleClickedRow=currentDoubleClickedRow, currentSelectedRows=currentSelectedRows, currentSorting=currentSorting, title=title, columns=columns, data=data, keyField=keyField, striped=striped, highlightOnHover=highlightOnHover, pointerOnHover=pointerOnHover, className=className, style=style, responsive=responsive, disabled=disabled, overflowY=overflowY, overflowYOffset=overflowYOffset, dense=dense, noTableHead=noTableHead, persistTableHead=persistTableHead, direction=direction, selectableRows=selectableRows, selectableRowsVisibleOnly=selectableRowsVisibleOnly, selectableRowsHighlight=selectableRowsHighlight, selectableRowsNoSelectAll=selectableRowsNoSelectAll, sortServer=sortServer, expandableRows=expandableRows, expandOnRowClicked=expandOnRowClicked, expandOnRowDoubleClicked=expandOnRowDoubleClicked, expandableRowsHideExpander=expandableRowsHideExpander, defaultSortField=defaultSortField, defaultSortAsc=defaultSortAsc, pagination=pagination, paginationServer=paginationServer, paginationDefaultPage=paginationDefaultPage, paginationPerPage=paginationPerPage, paginationRowsPerPageOptions=paginationRowsPerPageOptions, paginationTotalRows=paginationTotalRows, noHeader=noHeader, fixedHeader=fixedHeader, fixedHeaderScrollHeight=fixedHeaderScrollHeight)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DashDataTable',
        namespace = 'dash_data_table',
        propNames = c('id', 'containerClassName', 'containerStyle', 'currentPage', 'currentRowsPerPage', 'currentClickedRow', 'currentDoubleClickedRow', 'currentSelectedRows', 'currentSorting', 'title', 'columns', 'data', 'keyField', 'striped', 'highlightOnHover', 'pointerOnHover', 'className', 'style', 'responsive', 'disabled', 'overflowY', 'overflowYOffset', 'dense', 'noTableHead', 'persistTableHead', 'direction', 'selectableRows', 'selectableRowsVisibleOnly', 'selectableRowsHighlight', 'selectableRowsNoSelectAll', 'sortServer', 'expandableRows', 'expandOnRowClicked', 'expandOnRowDoubleClicked', 'expandableRowsHideExpander', 'defaultSortField', 'defaultSortAsc', 'pagination', 'paginationServer', 'paginationDefaultPage', 'paginationPerPage', 'paginationRowsPerPageOptions', 'paginationTotalRows', 'noHeader', 'fixedHeader', 'fixedHeaderScrollHeight'),
        package = 'dashDataTable'
        )

    structure(component, class = c('dash_component', 'list'))
}
