name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Install dependencies
      run: |
        poetry install
        npm install
    - name: Build a binary wheel and a source tarball
      run: poetry build
    - name: Publish distribution 📦 to Test PyPI
      run: poetry publish --repository https://test.pypi.org/legacy/ --username __token__ --password ${{ secrets.PYPI_API_TEST_TOKEN }}
    - name: Publish distribution 📦 to PyPI
      run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
